# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 278775bbec65f5582682162ef0b28d819bfcf6f5ac034b2860e60719f50510d64cea2d628b948dfc20ff3454e3d712c92282b023b885991bedb5094761ca0f54

test:
  secret_key_base: 61d385014db4760c6b1a5db99e059ec060e5766195902312ea01ab567287da5c8b381de66a586a5a1ea3f9d551f36c669f26976ae98c1a40e50321a8da856375

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
